/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current Ori user
         * @description Returns GitHub identity for the authenticated Ori account.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ori limits
         * @description Check quota, access readiness, and concurrent-ori capacity for the authenticated account.
         */
        get: operations["limits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List GitHub repositories available to Ori
         * @description Returns GitHub repositories grouped by installation plus the current selected repositories for new Oris.
         */
        get: operations["repos"];
        put?: never;
        /**
         * Select repository for Oris
         * @description Idempotently selects one repository for the Ori environment. Use `databaseId` from `GET /repos` as `repositoryId`; selecting an already-selected repository updates its `baseBranch`.
         */
        post: operations["selectRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Lists API key metadata only. Raw key secrets are not returned after creation/rotation. Results are scoped to the authenticated Ori account.
         */
        get: operations["apiKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ori secrets setup
         * @description Returns the environment variables and secret files configured for Oris.
         */
        get: operations["secrets"];
        put?: never;
        /** Update Ori secrets setup */
        post: operations["updateSecrets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List oris */
        get: operations["oris"];
        put?: never;
        /**
         * Create ori
         * @description Provision a new cloud computer. Store the returned `ori.id` with your product job/session record.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        /**
         * Get ori
         * @description Poll this endpoint after create, stop, resume, or fork operations.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update ori */
        patch: operations["update"];
        trace?: never;
    };
    "/oris/{oriId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop and archive ori
         * @description Stop active work and archive/snapshot the ori for later resume or fork.
         *
         *     A stop always saves the ori's disk first. If that save is failing, the stop is
         *     refused and the ori keeps running so your work is not discarded, we retry
         *     automatically and email you. You are not billed for time spent in that state.
         *
         *     Set `force: true` to stop anyway, accepting the loss of everything written since
         *     the last successful snapshot. This is irreversible; only reach for it after a
         *     stop has already failed.
         */
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume ori */
        post: operations["resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork ori */
        post: operations["fork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prompt Ori
         * @description Queue a natural-language work item for Codex or Claude Code inside the ori. Observe progress with `GET /oris/{oriId}/events`.
         */
        post: operations["prompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ori events
         * @description Return Ori work, lifecycle, and progress events so product UIs can show what the ori is doing. Event payloads are extensible. Clients can long-poll this endpoint with `sort=asc` and a cursor to stream responses. Response events expose agent text, streaming partials via `data.is_streaming`, and tool calls/results via `data.tools`.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/prompts/{promptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get prompt run status
         * @description Returns first-class status for a queued/running/finished prompt so clients do not infer completion from ori state and events.
         */
        get: operations["promptRunStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a file from a Ori */
        get: operations["readFile"];
        /** Write a file in a Ori */
        put: operations["writeFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a command in a Ori */
        post: operations["command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a Ori artifact */
        get: operations["artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt running work */
        post: operations["interrupt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/desktop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get desktop streaming URL
         * @description Create or fetch a secret-bearing desktop/noVNC URL for live computer-use visibility. Use `?vnc=1` for noVNC; a `provisioning: true` response means poll again.
         */
        post: operations["desktop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/sshkey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure ori SSH key
         * @description Adds an OpenSSH public key to the running Ori so the caller can SSH as user `user`.
         */
        post: operations["sshKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List snapshots
         * @description List completed snapshots across all of your oris, newest first. Each item carries the `oriId` it belongs to.
         */
        get: operations["listSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ori snapshots
         * @description List completed snapshots for one ori, newest first.
         */
        get: operations["listOriSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oris/{oriId}/snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest ori snapshot
         * @description Return the most recent completed snapshot for this ori, or `null` if it has none.
         */
        get: operations["getLatestOriSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshotId}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get snapshot file tree
         * @description List the files and folders captured in a snapshot, with sizes. Returns a flat list of entries you can render as a tree.
         */
        get: operations["getSnapshotTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshotId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file or folder from a snapshot
         * @description Stream a single file's bytes, or a folder subtree as a tar archive, directly out of a snapshot, the ori can be stopped or archived; the machine is never contacted. Use `GET /snapshots/{snapshotId}/tree` to list paths, then pass one here. Paths are relative to the snapshot root (same space as `tree` entries; docker volumes under `__dockervol__/`). An empty or `/` path downloads the whole snapshot as a tar. Folder responses set `X-Snapshot-File-Count`, `X-Snapshot-Total-Size-Bytes` and `X-Snapshot-Skipped-Base-Image-Files` headers; both response shapes set `X-Snapshot-Entry-Kind` (`file` or `dir`).
         */
        get: operations["getSnapshotFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshotId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get snapshot download
         * @description Return time-limited signed URLs for every chunk needed to reconstruct the ori filesystem at this snapshot (the full chain, base through this generation), plus the inventory. Download the chunks and reassemble them as described by `reconstruct`. The `ori snapshot pull` CLI command does this for you.
         */
        get: operations["getSnapshotDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessBase: {
            /** @example true */
            ok: boolean;
            /** @description Stable success envelope discriminator added by v1. */
            type: string;
        };
        ErrorEnvelope: {
            /** @example false */
            ok: boolean;
            /** @example ori.error */
            type: string;
            /** @example 409 */
            status: number;
            /** @example provider_not_configured */
            code: string;
            /** @example Prompting is locked until Codex is configured on the Agents page. */
            message: string;
            /** @example req_01HX... */
            requestId: string;
            error: {
                code: string;
                message: string;
                status: number;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Ori: {
            /** @example or_23456789 */
            id: string;
            /** @example Ori 2026-05-31 12:00 */
            name: string;
            /** @enum {string} */
            state: "init" | "provisioning" | "provisioned" | "cloning" | "ready" | "idle" | "running" | "archiving" | "archived" | "error";
            /**
             * @description Machine size this ori was created with. Fixed for the life of the ori.
             * @enum {string}
             */
            type?: "small" | "default" | "large" | "bare-metal";
            /**
             * @description vCPUs guaranteed by this ori's type.
             * @example 4
             */
            vcpu?: number;
            /**
             * @description RAM in GB guaranteed by this ori's type.
             * @example 8
             */
            memoryGB?: number;
            /**
             * @description Rate at which this ori consumes machine time. 0.5 for `small`, 1 for `default`, 2 for `large`.
             * @example 1
             */
            billingMultiplier?: number;
            /**
             * Format: uri
             * @description Machine URL when assigned.
             */
            url?: string | null;
            /** @description Machine IPv4 address when assigned. */
            ip?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            /**
             * Format: date-time
             * @description Automatic archival time, or null when auto-stop is disabled.
             */
            archiveAfter?: string | null;
            desktopAvailable: boolean;
            /**
             * Format: uri
             * @description Secret-bearing desktop stream URL when available. Redact from logs.
             */
            desktopUrl?: string | null;
            snapshotAvailable: boolean;
            /**
             * Format: date-time
             * @description Timestamp of the most recent successfully completed snapshot, or null.
             */
            snapshotCompletedAt?: string | null;
            /** @description The ori's stable three-word subdomain slug (e.g. "frazil-pneuma-rallye"), or null before one is assigned. */
            subdomain?: string | null;
            /**
             * Format: date-time
             * @description Timestamp of the most recent snapshot attempt of any status (queued, in_progress, completed, failed, cancelled), or null. Use with snapshotCompletedAt to detect snapshots that keep failing.
             */
            lastSnapshotAttemptAt?: string | null;
            /**
             * @description Status of the most recent snapshot attempt, or null if none. A value other than completed while snapshotCompletedAt stays stale indicates failing snapshots.
             * @enum {string|null}
             */
            lastSnapshotStatus?: "queued" | "in_progress" | "completed" | "failed" | "cancelled" | null;
        };
        ApiKey: {
            /** @example sak_123 */
            id: string;
            /** @example Production worker */
            name: string;
            /** @example ori_live */
            keyPrefix: string;
            /** @example 9abc */
            keyLastFour: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
        };
        Repository: {
            /** @description GitHub repository id. */
            id?: number;
            /** @description Internal repository id used when selecting repositories. */
            databaseId?: string;
            name?: string;
            /** @example acme/web */
            fullName?: string;
            private?: boolean;
            permissions?: string;
            /** Format: date-time */
            pushedAt?: string | null;
        } & {
            [key: string]: unknown;
        };
        SelectedRepository: components["schemas"]["Repository"] & {
            /** @example main */
            baseBranch?: string;
            setupRoutineId?: string | null;
            setupScript?: string;
            setupBlocking?: boolean;
            preCommitHooks?: {
                id?: string;
                script?: string;
                blocking?: boolean;
            }[];
        };
        RepositoryInstallation: {
            /** @example Organization */
            type?: string;
            /** @example acme */
            accountLogin?: string;
            /** Format: uri */
            accountAvatarUrl?: string | null;
            repositories?: components["schemas"]["Repository"][];
        };
        SecretFile: {
            /** @example .config/service-account.json */
            path: string;
            /** @description Secret file contents. Treat as sensitive. */
            contents: string;
        };
        LimitsFields: {
            /** @example trial */
            accessTier?: string;
            blockedReason?: string | null;
            currentLimits?: {
                activeOris?: number;
                creationRatePerMinute?: number;
                creationRequestsPerDay?: number | null;
            } & {
                [key: string]: unknown;
            };
            standardLimits?: {
                activeOris?: number;
                creationRatePerMinute?: number;
                creationRequestsPerDay?: number | null;
            } & {
                [key: string]: unknown;
            };
            trialLimits?: {
                activeOris?: number;
                creationRatePerMinute?: number;
                creationRequestsPerDay?: number | null;
            } & {
                [key: string]: unknown;
            };
            upgradeEffects?: {
                [key: string]: unknown;
            };
            /** @description Whether the authenticated account can create or operate oris right now. */
            canStart: boolean;
            checkoutRequired?: boolean;
            startBlockedReason?: string | null;
            contactMessage?: string | null;
            activeOris: number;
            activeStates?: string[];
            maxActiveOris: number;
            maxCreationRequestsPerMinute?: number;
            maxCreationRequestsPerDay?: number | null;
            hasPaymentHistory?: boolean;
            package?: {
                [key: string]: unknown;
            };
            subscriptionQuotaSeconds?: number;
            subscriptionRemainingSeconds?: number;
            packBalanceSeconds?: number;
            creditPurchasedSeconds?: number;
            creditUsedSeconds?: number;
            liveUsageSeconds?: number;
            creditSecondsPerDollar?: number;
            /** @description Account access state returned by the current backend. Billing endpoints are not part of v1. */
            billingStatus: string;
            subscriptionStatus?: string | null;
            subscriptionCancelAtPeriodEnd?: boolean;
            hasSubscription?: boolean;
            /** Format: date-time */
            subscriptionTrialEndsAt?: string | null;
            /** Format: date-time */
            subscriptionCurrentPeriodEnd?: string | null;
            creditBalanceSeconds?: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Options for provisioning a new cloud computer.
         * @example {
         *       "ttlSeconds": 3600
         *     }
         * @example {
         *       "ttlSeconds": null
         *     }
         * @example {
         *       "type": "large",
         *       "ttlSeconds": 3600
         *     }
         * @example {
         *       "ttlSeconds": 3600,
         *       "env": {
         *         "DATABASE_URL": "postgres://user:pass@host:5432/app",
         *         "FEATURE_FLAG": "1"
         *       }
         *     }
         * @example {
         *       "ttlSeconds": null,
         *       "noEnv": true
         *     }
         */
        CreateOriRequest: {
            /**
             * @description Machine size. `small` is 2 vCPUs / 4 GB RAM and consumes machine time at half rate; `default` is 4 vCPUs / 8 GB RAM; `large` is 8 vCPUs / 16 GB RAM and consumes machine time twice as fast (see the Billing guide). A ori keeps its type for life: stopping, resuming and forking all preserve it, and forks inherit the source ori's type.
             * @default default
             * @enum {string}
             */
            type: "small" | "default" | "large";
            /**
             * @description Number of seconds before automatic archival. `null` disables auto-stop. The backend also accepts the string `infinite` for legacy compatibility; new clients should send null.
             * @default 3600
             */
            ttlSeconds: number | null;
            /** @description Per-ori environment variables injected into the ori's tool environment, on top of the account environment's variables (per-ori values win on conflicts). Keys must match `[A-Za-z_][A-Za-z0-9_]{0,127}`; at most 100 variables and 64KB total. Reserved names (`ORI_ID`, `ORI_AGENT_TOKEN`, `ORI_MACHINE_TOKEN`, `ORI_CONTROL_PLANE`, `ORI_CLI_TOKEN`) are rejected with `invalid_env`. Forked oris inherit the source ori's env unless the fork request supplies its own `env`. */
            env?: {
                [key: string]: string;
            };
            /**
             * @description Create a ori with none of the secrets attached to your account (no environment variables, secret files, or credentials), confined to itself so it cannot act on your account or other oris. For oris you give to your own users. SSH, SCP, desktop, snapshots, and public URLs still work; pass `env` to give the ori a secret of its own. A fork of a no-env ori is always no-env.
             * @default false
             */
            noEnv: boolean;
        };
        /** @description Options for stopping a Ori. */
        StopRequest: {
            /**
             * @description Stop the ori even if its disk cannot be snapshotted. Everything written since the last successful snapshot is permanently LOST. Without this, a ori whose snapshot pipeline is failing is left running rather than discarding your work, and you are not billed for that time. Only use this after a stop has already been refused.
             * @default false
             */
            force: boolean;
        };
        /** @description Options for resuming a stopped Ori. */
        ResumeRequest: {
            /**
             * @description Resume onto a different machine size. Omit to keep the ori's current type. A resume already restores onto a fresh machine, so changing size costs nothing extra. Shrinking is rejected with `type_too_small` when the ori's data would not fit the smaller disk.
             * @enum {string}
             */
            type?: "small" | "default" | "large";
            /** @description Resume into a no-env ori: withhold account secrets and scrub inherited owner secrets from the restored snapshot before the ori is exposed. One-way; once a ori is resumed as no-env it stays no-env on later resumes. */
            noEnv?: boolean;
        };
        /**
         * @example {
         *       "name": "Customer support run",
         *       "ttlSeconds": 7200
         *     }
         * @example {
         *       "subdomain": "acme-staging"
         *     }
         */
        UpdateOriRequest: {
            /** @description New display name. Empty strings are rejected; longer names are truncated to 120 chars by the backend. */
            name?: string;
            /** @description New archival TTL. `null` disables auto-stop. */
            ttlSeconds?: number | null;
            /** @description Rename the Ori's stable subdomain (the `<subdomain>.on.example.com` label). Lowercase letters, digits and hyphens; no leading/trailing/double hyphens; cannot end in `-desktop` or `-<number>` (reserved for the desktop and hosted-port URLs). Must be globally unique. The base URL, desktop URL and every live `host <port>` URL are re-pointed to the new name with no downtime and their access tokens preserved; the old URLs stop resolving. On a transient routing error the rename is saved but returns 502 `gateway_error` - retry with the same value to finish activating routes. */
            subdomain?: string;
        };
        /**
         * @description Work item to queue inside an existing Ori. Provider credentials must already be configured in the Ori dashboard.
         *
         *     Provider values: `codex`, `claude-code`; the backend currently also accepts `claude` as an alias for `claude-code`.
         *
         *     Recommended model ids come from `backend/models.json`: Codex `gpt-5.5`, `gpt-5.4`, `gpt-5.4-mini`, `gpt-5.3-codex`; Claude Code `claude-fable-5`, `opus`, `sonnet`, `haiku`. If omitted, the user's saved provider default is used.
         * @example {
         *       "provider": "codex",
         *       "model": "gpt-5.4",
         *       "reasoningEffort": "medium",
         *       "prompt": "Work on the selected repo, run tests, fix failures, commit the result, and report any hosted preview URL."
         *     }
         */
        PromptRequest: {
            /** @enum {string} */
            provider: "codex" | "claude-code" | "claude";
            /**
             * @description Optional provider model id. Prefer the documented ids; unknown explicit ids are currently forwarded rather than rejected by request validation.
             * @example gpt-5.4
             * @example claude-fable-5
             * @example sonnet
             */
            model?: string | null;
            /**
             * @description Optional reasoning effort. Codex supports `none`, `low`, `medium`, `high`, `xhigh` for GPT-5.4/5.5/5.4-mini and `low`, `medium`, `high`, `xhigh` for GPT-5.3 Codex. Claude `claude-fable-5` and `opus` support `low`, `medium`, `high`, `max`; `sonnet` supports `low`, `medium`, `high`; `haiku` has no reasoning control.
             * @example medium
             */
            reasoningEffort?: string | null;
            /** @description Natural-language task for the Ori, including repo, preview, or browser-use instructions. */
            prompt: string;
        };
        /**
         * @description Idempotently selects a repository for future Oris. If the repository is already selected, the API updates its base branch instead of returning a conflict.
         * @example {
         *       "repositoryId": "repo_org_123",
         *       "baseBranch": "dev"
         *     }
         */
        RepoSelectionRequest: {
            /** @description Internal repository `databaseId` returned by `GET /repos`. */
            repositoryId: string;
            /** @default main */
            baseBranch: string;
        };
        /**
         * @description Full replacement for the Ori secret setup. Omitted `envContents` or `secretFiles` are treated as empty values, and successful updates are pushed to active Oris.
         * @example {
         *       "envContents": "OPENAI_API_KEY=sk-...\nDATABASE_URL=postgres://...",
         *       "secretFiles": [
         *         {
         *           "path": ".config/service-account.json",
         *           "contents": "{\"type\":\"service_account\"}"
         *         }
         *       ]
         *     }
         */
        SecretsUpdateRequest: {
            /** @description Full .env-style content to sync into Oris. Send the complete desired file contents, not a patch. */
            envContents?: string;
            /** @description Full list of secret files to keep configured. Send existing files again if they should remain. */
            secretFiles?: components["schemas"]["SecretFile"][];
        };
        SshKeyRequest: {
            /**
             * @description Public SSH key in OpenSSH format. Private keys are rejected.
             * @example ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA... user@host
             */
            key: string;
        };
        /** @description Optional desktop/VNC setup options used by the Ori dashboard and CLI. Most callers send an empty body. */
        DesktopRequest: {
            /**
             * @description For `?vnc=1`, return a noVNC URL that does not require an access token.
             * @default false
             */
            publicAccess: boolean;
        } & {
            [key: string]: unknown;
        };
        MeResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "user.info";
            user: {
                login?: string;
                email?: string | null;
            };
        };
        LimitsResponse: components["schemas"]["SuccessBase"] & components["schemas"]["LimitsFields"];
        ReposResponse: components["schemas"]["SuccessBase"] & {
            installations: components["schemas"]["RepositoryInstallation"][];
            environmentId: string;
            selectedRepositories: components["schemas"]["SelectedRepository"][];
            pageInfo?: components["schemas"]["PageInfo"];
        };
        RepoSelectionResponse: components["schemas"]["SuccessBase"] & {
            success: boolean;
            environmentId: string;
            selectedRepositories: components["schemas"]["SelectedRepository"][];
        };
        SecretsResponse: components["schemas"]["SuccessBase"] & {
            success?: boolean;
            environmentId: string;
            envContents: string;
            secretFiles: components["schemas"]["SecretFile"][];
            /** @description Present on update; counts how many active Oris received the new environment. */
            pushed?: {
                [key: string]: unknown;
            };
        };
        OriListResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "ori.list";
            oris: components["schemas"]["Ori"][];
            pageInfo?: components["schemas"]["PageInfo"];
        };
        OriInfoResponse: components["schemas"]["SuccessBase"] & {
            /** @example ori.info */
            type?: string;
            ori: components["schemas"]["Ori"];
        };
        CreateOriResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "ori.created";
            /** @enum {string} */
            status: "provisioning";
            ttlSeconds: number | null;
            ori: components["schemas"]["Ori"];
        };
        OriActionResponse: components["schemas"]["SuccessBase"] & {
            /** @example ori.stopping */
            type?: string;
            id: string;
            /** @example archiving */
            status: string;
            ori?: components["schemas"]["Ori"] | null;
        };
        PageInfo: {
            nextCursor: string | null;
            hasMore: boolean;
            limit: number;
        };
        EventPageInfo: components["schemas"]["PageInfo"] & {
            /** @description Cursor positioned strictly after the last event on this page, for long-polling with `sort=asc`. Unlike `nextCursor` (null once the page is the last one), this is always usable to ask for whatever arrives next; it is null only when the ori has no events at all. */
            followCursor: string | null;
        };
        PromptRun: {
            id: string;
            promptId: string;
            oriId: string;
            /** @enum {string} */
            status: "sending" | "queued" | "running" | "finished" | "failed";
            done: boolean;
            /** Format: date-time */
            createdAt?: string | null;
            model?: string | null;
            reasoningEffort?: string | null;
        };
        PromptRunResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "prompt.run";
            id: string;
            promptRun: components["schemas"]["PromptRun"];
        };
        OriEvent: {
            id?: string;
            type: string;
            timestamp?: number;
            taskId?: string | null;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        UnknownEvent: {
            type: string;
        } & {
            [key: string]: unknown;
        };
        PromptEvent: {
            id: string;
            /** @constant */
            type: "prompt";
            timestamp: number;
            taskId?: string | null;
            data: {
                prompt: string;
                /** @enum {string} */
                status: "sending" | "queued" | "running" | "finished" | "failed";
                is_reverted?: boolean;
            };
        };
        /** @description Agent response event. Text deltas/finals and tool-call batches are both represented as response events; tool-call batches have `data.tools`. */
        ResponseEvent: {
            id: string;
            /** @constant */
            type: "response";
            timestamp: number;
            taskId?: string | null;
            data: {
                content: string;
                model?: string | null;
                /** @description Tool call/result records emitted by the agent. Present for tool-call events and omitted for text-only response events. */
                tools?: {
                    [key: string]: unknown;
                }[];
                /** @description True when this response is a streaming partial rather than the final assistant message. */
                is_streaming?: boolean;
            };
        };
        GitCheckpointEvent: {
            id: string;
            /** @constant */
            type: "git_checkpoint";
            timestamp: number;
            taskId?: string | null;
            data: {
                commitSha: string;
                commitMessage: string;
                commitUrl?: string | null;
                branch: string;
                filesChanged?: number;
                additions?: number;
                deletions?: number;
                pushed?: boolean;
            };
        };
        ErrorEvent: {
            id: string;
            /** @enum {string} */
            type: "usage_limit" | "shield";
            timestamp: number;
            taskId?: string | null;
            data: {
                [key: string]: unknown;
            };
        };
        CompletionEvent: {
            id: string;
            /** @enum {string} */
            type: "task_notification" | "compaction_complete";
            timestamp: number;
            taskId?: string | null;
            data: {
                [key: string]: unknown;
            };
        };
        FileReadResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "file.read";
            success: boolean;
            path: string;
            /** @enum {string} */
            encoding: "utf8" | "base64";
            size: number;
            content: string;
        };
        FileWriteRequest: {
            /** @description Relative path inside the Ori work directory. */
            path: string;
            content: string;
            /**
             * @default utf8
             * @enum {string}
             */
            encoding: "utf8" | "base64";
        };
        FileWriteResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "file.written";
            success: boolean;
            path: string;
            /** @enum {string} */
            encoding: "utf8" | "base64";
            size: number;
        };
        CommandRequest: {
            command: string;
            /** @description Relative working directory inside the Ori work directory. */
            cwd?: string;
            /** @default 30 */
            timeoutSeconds: number;
        };
        CommandResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "command.finished";
            success: boolean;
            exitCode: number | null;
            signal?: string | null;
            stdout: string;
            stderr: string;
            stdoutTruncated?: boolean;
            stderrTruncated?: boolean;
            timedOut: boolean;
            cwd?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        PromptResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "prompt.queued";
            /** @description Ori id. */
            id: string;
            promptId: string;
            promptRun: components["schemas"]["PromptRun"];
            /** @enum {string} */
            status: "queued";
            provider: string;
            model?: string | null;
            reasoningEffort?: string | null;
        };
        EventsResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "events.list";
            id: string;
            /** @description Ori work and lifecycle event objects. Event shapes are intentionally extensible; branch on each event `type` when present. */
            events: components["schemas"]["OriEvent"][];
            pageInfo?: components["schemas"]["EventPageInfo"];
        };
        DesktopResponse: components["schemas"]["SuccessBase"] & ({
            /** @example desktop.url */
            type?: string;
            success?: boolean;
            /**
             * Format: uri
             * @description Secret-bearing desktop or noVNC URL. Redact from logs.
             */
            desktopUrl?: string | null;
            ip?: string | null;
            /** @example vnc */
            mode?: string;
            /** @description For `?vnc=1`, true means VNC is still being prepared; poll again. */
            provisioning?: boolean;
            message?: string;
        } & {
            [key: string]: unknown;
        });
        SshKeyResponse: components["schemas"]["SuccessBase"] & {
            success?: boolean;
            machineIp?: string | null;
            /** @example user */
            sshUser?: string;
        };
        ApiKeysResponse: components["schemas"]["SuccessBase"] & {
            apiKeys: components["schemas"]["ApiKey"][];
        };
        SnapshotSummary: {
            /** Format: uuid */
            id: string;
            /** @description Public Ori id this snapshot belongs to. */
            oriId: string;
            /** @enum {string} */
            status: "completed";
            /**
             * @description `base` (full) or `incremental` (delta on a base). `null` for legacy snapshots.
             * @enum {string|null}
             */
            kind?: "base" | "incremental" | null;
            /** @description Position in the incremental chain (0 = base). */
            generation: number;
            /** Format: uuid */
            chainId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            /** @description Bytes this snapshot added (its delta), not the full restored size. */
            sizeBytes: number;
            /** @description Inventory entries alive in the chain at this generation (includes base-image system entries). */
            fileCount: number;
            /** @description Total bytes of your data restored by this snapshot (what resume/download returns; base image excluded). `null` on legacy snapshots. */
            contentSizeBytes?: number | null;
            /** @description Number of your files restored by this snapshot (base image excluded). `null` on legacy snapshots. */
            contentFileCount?: number | null;
        };
        SnapshotListResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "snapshot.list";
            snapshots: components["schemas"]["SnapshotSummary"][];
            pageInfo?: components["schemas"]["PageInfo"];
        };
        SnapshotLatestResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "snapshot.latest";
            snapshot: components["schemas"]["SnapshotSummary"] | null;
        };
        SnapshotTreeEntry: {
            /** @description Path relative to the snapshot root. Docker named volumes appear under `__dockervol__/`. */
            path: string;
            /** @enum {string} */
            kind: "file" | "dir" | "symlink";
            /** @description File size in bytes. Omitted for directories. */
            size?: number;
        };
        SnapshotTreeResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "snapshot.tree";
            /** Format: uuid */
            snapshotId: string;
            oriId: string;
            generation: number;
            /** @description `false` for legacy snapshots or inventories too large to expand; see `reason`. */
            treeAvailable: boolean;
            /** @description `true` when the file list was capped; not every entry is returned. */
            truncated: boolean;
            /** @description Number of your files in this snapshot (base-image system files excluded). */
            fileCount: number;
            /** @description Total bytes of your data in this snapshot (base-image system files excluded). */
            totalSizeBytes: number;
            /** @description Exactly the files/dirs a resume or download returns, your data only; base-image system entries are not listed. */
            entries: components["schemas"]["SnapshotTreeEntry"][];
            /**
             * @description Why the tree is unavailable, when `treeAvailable` is `false`.
             * @example legacy_snapshot
             * @example inventory_too_large
             */
            reason?: string;
        };
        SnapshotChunk: {
            /** Format: uuid */
            snapshotId: string;
            generation: number;
            chunkIndex: number;
            r2Key: string;
            sizeBytes: number;
            sha256: string;
            /**
             * Format: uri
             * @description Time-limited download URL (see `expiresInSeconds`).
             */
            signedUrl: string;
        };
        SnapshotDownloadResponse: components["schemas"]["SuccessBase"] & {
            /** @constant */
            type?: "snapshot.download";
            /** Format: uuid */
            snapshotId: string;
            oriId: string;
            /** @enum {string} */
            kind: "base" | "incremental" | "legacy";
            generation: number;
            /** @description Lifetime of every `signedUrl` in this response. */
            expiresInSeconds: number;
            /** @description Human-readable note on how to reassemble the chunks into a filesystem. */
            reconstruct: string;
            inventory?: {
                r2Key: string;
                /** Format: uri */
                signedUrl: string;
            } | null;
            /** @description Every chunk across the chain (all generations up to and including this snapshot), ordered by `(generation, chunkIndex)`. */
            chunks: components["schemas"]["SnapshotChunk"][];
        };
    };
    responses: {
        /** @description Invalid request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated token is not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Account cannot currently create or operate Oris. The error body may include a dashboard billing URL, but billing actions are not part of the v1 API. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request conflicts with current account or ori state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Machine start or concurrent-ori limit reached. Create, fork and resume each count as one machine start against your plan's per-minute rate (`rate_limited`) and against the platform ceilings of 600 starts per hour and 1500 per day (`start_limit_reached`). */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Public Ori id returned by create/list/get ori calls. */
        OriId: string;
        /** @description Maximum items to return. */
        Limit: number;
        /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
        Cursor: string | null;
        /** @description Sort direction for cursor pagination. */
        Sort: "asc" | "desc";
        /** @description Snapshot id returned by the snapshot list/latest calls. */
        SnapshotId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    limits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current creation and concurrent-ori limits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    repos: {
        parameters: {
            query?: {
                /** @description When true, sync from GitHub before returning repository groups. */
                sync?: boolean;
                /** @description Maximum items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort direction for cursor pagination. */
                sort?: components["parameters"]["Sort"];
                /** @description Case-insensitive repository name/fullName filter. */
                q?: string;
                /** @description Filter to selected or unselected repositories. */
                selected?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository groups and current Ori repository selection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    selectRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoSelectionRequest"];
            };
        };
        responses: {
            /** @description Updated repository selection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSelectionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    apiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeysResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    secrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current secret setup metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated secret setup metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    oris: {
        parameters: {
            query?: {
                /** @description Maximum items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort direction for cursor pagination. */
                sort?: components["parameters"]["Sort"];
                /** @description Comma-separated Ori state filter, for example `ready,idle,running`. */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oris owned by the authenticated Ori user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateOriRequest"];
            };
        };
        responses: {
            /** @description Ori accepted for provisioning. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOriResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ori details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriInfoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOriRequest"];
            };
        };
        responses: {
            /** @description Updated ori details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriInfoResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StopRequest"];
            };
        };
        responses: {
            /** @description Ori archival started or already in progress. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    resume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Resume started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    fork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Replaces the env the fork would otherwise inherit from the source ori. Same validation rules as `CreateOriRequest.env`. */
                    env?: {
                        [key: string]: string;
                    };
                    /** @description Make the fork no-env (see `CreateOriRequest.noEnv`). A fork of a no-env ori is always no-env regardless of this field. */
                    noEnv?: boolean;
                    /**
                     * @description Machine size for the fork. Omit to inherit the source ori's type. The source ori is never modified. Shrinking is rejected with `type_too_small` when the source's data would not fit the smaller disk.
                     * @enum {string}
                     */
                    type?: "small" | "default" | "large";
                };
            };
        };
        responses: {
            /** @description Fork started. The response `id` is the new forked ori id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    prompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequest"];
            };
        };
        responses: {
            /** @description Prompt queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    events: {
        parameters: {
            query?: {
                /** @description Maximum items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort direction for cursor pagination. */
                sort?: components["parameters"]["Sort"];
                /** @description Comma-separated event type filter, for example `prompt,response,git_checkpoint`. */
                type?: string;
            };
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ori work and lifecycle events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    promptRunStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt run status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    readFile: {
        parameters: {
            query: {
                path: string;
                encoding?: "utf8" | "base64";
            };
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileReadResponse"];
                };
            };
        };
    };
    writeFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileWriteRequest"];
            };
        };
        responses: {
            /** @description File written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileWriteResponse"];
                };
            };
        };
    };
    command: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Command result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
        };
    };
    artifact: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    interrupt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interrupt requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    desktop: {
        parameters: {
            query?: {
                /** @description Use VNC/noVNC streaming mode. */
                vnc?: 1;
                /** @description Desktop streaming theme for non-VNC mode. */
                theme?: "light" | "dark";
            };
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DesktopRequest"];
            };
        };
        responses: {
            /** @description Desktop streaming URL, or provisioning state for VNC setup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesktopResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    sshKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SshKeyRequest"];
            };
        };
        responses: {
            /** @description SSH key setup result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SshKeyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    listSnapshots: {
        parameters: {
            query?: {
                /** @description Maximum items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort direction for cursor pagination. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed snapshots owned by the authenticated Ori user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listOriSnapshots: {
        parameters: {
            query?: {
                /** @description Maximum items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor returned as `pageInfo.nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Sort direction for cursor pagination. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed snapshots for this ori. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLatestOriSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public Ori id returned by create/list/get ori calls. */
                oriId: components["parameters"]["OriId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent completed snapshot, or `null`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotLatestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSnapshotTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Snapshot id returned by the snapshot list/latest calls. */
                snapshotId: components["parameters"]["SnapshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flat file/folder listing for the snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSnapshotFile: {
        parameters: {
            query?: {
                /** @description File or folder path inside the snapshot. Empty for the whole snapshot. */
                path?: string;
            };
            header?: never;
            path: {
                /** @description Snapshot id returned by the snapshot list/latest calls. */
                snapshotId: components["parameters"]["SnapshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File bytes (`application/octet-stream`) or folder tar (`application/x-tar`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/x-tar": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Path has no downloadable bytes, one of `legacy_snapshot` (pre-inventory snapshot), `snapshot_not_indexed` (content captured before the indexed snapshot format; take a new snapshot or use the download bundle), `base_image_file` (stock image file, not stored in snapshots), or `is_symlink` (request the symlink's target instead). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSnapshotDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Snapshot id returned by the snapshot list/latest calls. */
                snapshotId: components["parameters"]["SnapshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed chunk URLs for the snapshot chain. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDownloadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
